/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/components/**/*.{js,vue,ts}",
    "./src/layouts/**/*.vue",
    "./src/pages/**/*.vue",
    "./src/plugins/**/*.{js,ts}",
    "./src/nuxt.config.{js,ts}",
    "./src/app.vue",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: "#eff6ff",
          100: "#dbeafe",
          200: "#bfdbfe",
          300: "#93c5fd",
          400: "#60a5fa",
          500: "#3b82f6",
          600: "#2563eb",
          700: "#1d4ed8",
          800: "#1e40af",
          900: "#1e3a8a",
        },
        custom: {
          dark: "#5c3e84",
          light: "#686ee2",
        },
      },
      fontFamily: {
        body: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "Noto Sans",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
        sans: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "Noto Sans",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
        mukha: ["Mukta", "sans-serif"],
        lobster: ["Lobster", "cursive"],
      },
      backgroundColor: {
        skyBlue: {
          50: "#42d2dc42",
          100: "#42d2dc5d",
          200: "#42d2dc70",
          300: "#42d2dc83",
          400: "#42d2dc9d",
          500: "#42d2dcad",
          600: "#42d2dcc2",
          700: "#42d2dcd8",
          800: "#42d2dcea",
          900: "#42d2dc",
        },
        lightBrown: {
          50: "#e4d2c548",
          100: "#e4d2c569",
          200: "#e4d2c56e",
          300: "#e4d2c5a2",
          400: "#e4d2c5bb",
          500: "#e4d2c5c9",
          600: "#e4d2c5d8",
          700: "#e4d2c5ea",
          800: "#e4d2c5f6",
          900: "#e4d2c5",
        },
      },
    },
    data: {
      collapse: 'ui~=""',
    },
  },
  plugins: [
    require("tailwindcss"),
    require("autoprefixer"),
  ],
}

